### ISSUE TITLE
Develop deployment that creates test job model data that includes mocked up relationships between jobs

### ISSUE THREAD

**Issue by kotfic** [girder/girder_worker#200]
This should give @ronichoudhury something to work with in terms of visualizing complex job dependencies.

@dorukozturk Can you chime in here with what the current job model attributes look like?  (parent_id? Is this the id of the parent celery task or the id of the parent job model?)

I am also hoping for @jbeezley's input (and recollection) on what changes need to happen to the job model to enable groups,  chaining, etc - as well as what options should be set on the model to define default display layouts.

**Comment by kotfic** [comment]
We would also benefit from @cjh1's attention to this issue as he has already implemented some client side visualizations of job relationships in  [Kitware/cumulus](https://github.com/Kitware/cumulus)

**Comment by dorukozturk** [comment]
Current job model has an argument called parentJob, which is an id for the parentJob to be assigned. On the Girder end it is always a Girder Job ID. When Girder-Worker is responsible for spinning up jobs, since worker end does not know about girder job ids, we pass along the celery parent task id and do a lookup on Mongo to find the corresponding Girder parent job. We can do that because each job document contains the celery task id if the job is created by Girder-Worker.

**Comment by ronichoudhury** [comment]
Has there been any progress on this?

**Comment by kotfic** [comment]
@ronichoudhury  Not directly,  thought this is a possible target for @sutartmelson to work on (in terms of concrete implementation)  once we've mocked up data.  I still need touch base with @jbeezley and @dorukozturk to see about generating this data.

**Comment by kotfic** [comment]
This is resolved with the jobmock tool: https://github.com/kotfic/girder_jobmock
