### ISSUE TITLE
Dealing with string inputs

### ISSUE THREAD

**Issue by rbaral** [girder/girder_worker#42]
I was interested in having dynamic text input (lets say the filename where I would like to save the blurred image, in the context of the example given in the documentation of girder worker). I created the outputFileName object and fed that to the execution of the save_image task. 
I am following the convention of the input image (the lenna object in the code below) to create the outputFileName.
However, I got the error (as posted below). Can you explain if this is a bug or point out the way to handle this. I read the whole doc of girderWorker but couldn't figure it out.
---------------------python code-----------girderWorkerStandAlone.py--------------
```
import girder_worker
from girder_worker.specs import Workflow
wf = Workflow()

#create an input object
lenna = {
    'type': 'image',
    'format': 'png',
    'url': 'https://upload.wikimedia.org/wikipedia/en/2/24/Lenna.png'
}

'''
task to save the image
'''
save_image = {
    'inputs': [
        {'name': 'the_image', 'type': 'image', 'format': 'pil'},
        {'name': 'file_Name', 'type': 'string', 'format': 'text'}
        ],
    'outputs': [],
    'script': '''
from datetime import datetime
#file_Name = '/home/vagrant/tangelo/tangelo_demo/proj/lenna__'+ datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]+'.jpg'
the_image.save(file_Name)
'''
}

outputFileName = {
        'type': 'string',
        'format': 'jpg',
        'text': "/home/vagrant/tangelo/tangelo_demo/proj/lennaimage.jpg"
}

#running the single task
output = girder_worker.run(save_image, {'the_image': lenna, 'file_Name': outputFileName})
```
-----------error----------
```
Traceback (most recent call last):
  File "girderWorkerStandAlone.py", line 37, in <module>
    output = girder_worker.run(save_image, {'the_image': lenna, 'file_Name': outputFileName})
  File "/home/vagrant/girder_env/local/lib/python2.7/site-packages/girder_worker/utils.py", line 291, in wrapped
    return fn(*args, **kwargs)
  File "/home/vagrant/girder_env/local/lib/python2.7/site-packages/girder_worker/__init__.py", line 251, in run
    d, **dict({'task_input': task_input}, **kwargs))
  File "/home/vagrant/girder_env/local/lib/python2.7/site-packages/girder_worker/io/__init__.py", line 104, in fetch
    return _fetch_map[mode](spec, **kwargs)
  File "/home/vagrant/girder_env/local/lib/python2.7/site-packages/girder_worker/io/__init__.py", line 31, in _inline_fetch
    return spec['data']
KeyError: 'data'
```

**Comment by jeffbaumes** [comment]
Your `outputFileName` structure has a few incorrect parts. `png` is not a valid format for type `string`, you should instead use `'format': 'text'`. Also, the string value should be stored in the `data` field instead of the a field named `text`. So if you replace your declaration of `outputFileName` to this it should work properly:

```
outputFileName = {
        'type': 'string',
        'format': 'text',
        'data': "/home/vagrant/tangelo/tangelo_demo/proj/lennaimage.jpg"
}
```

**Comment by rbaral** [comment]
Thanks. It worked! 
So, is the "data" field the one that is expected all the time? I saw in the image blurring example, the "lenna" object had "url" instead of the "data".
How can I make the worker execute a method instead of the inline script. The document says that we can execute a script or a function. But it doesn't recognize the function when called from inside the script part.

**Comment by jeffbaumes** [comment]
This documentation should be made more clear, but the required fields for specifying input data is described here:

http://girder-worker.readthedocs.io/en/latest/api-docs.html#the-input-specification

Note a few other bits of information that aren't spelled out clearly in the docs:
* A `type` field is not required when sending an input to a task. Any supplied `type` will be ignored, since the task defines the required type of each input. However, the `format` field is required because the format is allowed to differ from the task spec. If a different format is supplied, the data will be auto-converted before running the task.
* The `mode` field is inferred in a few special cases. If there is a `url` field, the `mode` is assumed to be `"http"`, and if there is a `data` field, the `mode` is assumed to be `"inline"`.

So the following input specs are equivalent:

```
{
    'format': 'text',
    'data': 'hello'
}
```

```
{
    'mode': 'inline',
    'format': 'text',
    'data': 'hello'
}
```

As well as the following:

```
{
    'format': 'png',
    'url': 'https://upload.wikimedia.org/wikipedia/en/2/24/Lenna.png'
}
```

```
{
    'mode': 'http',
    'format': 'png',
    'url': 'https://upload.wikimedia.org/wikipedia/en/2/24/Lenna.png'
}
```

I'll submit a PR to get this documentation in there.

**Comment by rbaral** [comment]
That's cool. Thanks!
