### ISSUE TITLE
Fixed version requirements cause problems

### ISSUE THREAD

**Issue by manthey** [girder/girder_worker#76]
I have a job that requires Pillow version >= 3.4, but girder_worker has Pillow 3.2.0 as a hard requirement.  The core plugins will NOT load with a different version of Pillow.  Requirements should allow a version range or only specify a minimum version unless there is a known reason to have a fixed version.

Since requirements.txt should be the frozen version used for testing, setup.py should either specify packages explicitly (rather than reading a file), or, when reading the requirements.txt file should change simple == version requirements to ~=.

**Comment by zachmullen** [comment]
👍  we should do what we do in girder itself and keep the versions in setup.py minimally constrained.

**Comment by Purg** [comment]
I have also encountered this issue but with a kombu version conflict (when extending the girder docker container to also run a girder-worker). Does girder-worker have any hard version requirements? Otherwise I have a local fix that reads requirements.txt files, stripping version restrictions in setup.py (also for plugins separate requirements.txt files). I could PR that if that's something that's desired.

**Comment by Purg** [comment]
Did #77 address this? Should this be closed?

**Comment by zachmullen** [comment]
#77 created a short-term solution, but is not the best one. I think we need something similar to what we have in Girder, where setup.py contains its own list that does not include transitive dependencies at all.

**Comment by kotfic** [comment]
I believe this is now resolved in https://github.com/girder/girder_worker/pull/202 If not,  please re-open!
