### ISSUE TITLE
Docker: support flag-type container args

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#85]
The Slicer CLI specification supports boolean input types, but does not allow them to be passed in the form of `--flag=false`, only `--flag` or not. We currently don't support this if the flag is a task input, but we could do so using a new token syntax in `container_args`, e.g.

    $flag{--bool-flag-name}

Which would be bound to a boolean input that would cause `--bool-flag-name` to be passed to the CLI if true, and omitted if false.

**Comment by jeffbaumes** [comment]
The only thing I don't like is that it requires you to make the id of the input name start with `--`.

I could see two ways to separate these concerns. One is that you make `$flag` take two inputs, the input id and the flag name. The other is to move some command argument logic to the input spec, so that there is both an `id` and an `arg` variable to help construct the flag (`arg` could default to `'--' + id`). I also could see the `--input_name=$input{input_name}` pattern repeated often, and the `arg` field with something like `$option{input_name}` that expands to the that pattern could handle that common case more cleanly.

**Comment by jeffbaumes** [comment]
As more syntactic sugar, it may be nice to add a single macro `$all` which expands to `$option{id1} $option{id2} ...` for all inputs in order. Probably would make sense to use `$flag{id}` for boolean inputs. There shouldn't be inputs that aren't reflected in the command line arguments to docker, so I expect this would cover many use cases.

**Comment by zachmullen** [comment]
I like the second proposal; in my first pass at this, I was just using `id` and `name` to distinguish between how it is passed on the command line (with dashes) versus how it is displayed to users. But having another, more explicit field for this in the task input would be better, e.g.:

```
id: "MyFlag"
name: "MyFlag"
flag: "--my-flag"
type: "boolean"
format: "boolean"
```

and if the `flag` field is not set, we can fall back to the `id`. Sound reasonable?

**Comment by jeffbaumes** [comment]
This is a good solution for `flag`, but if we ever implement the other syntactic sugar I suggested, it may be good to call the key something more generic (`arg` or something similar) so other non-boolean inputs could describe themselves as well.

**Comment by zachmullen** [comment]
Good point, I'll use `arg` then.
